name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: hazallul/spring-boot-app:${{ github.sha }}, hazallul/spring-boot-app:latest

    - name: Update Kubernetes deployment image
      uses: fjogeleit/yaml-update-action@main
      with:
        repository: Hazallul/Deneme
        token: ${{ secrets.PAT }}
        branch: main
        valueFile: Deployment.yaml
        changes: |
          {
            "spec.template.spec.containers[0].image": "hazallul/spring-boot-app:${{ github.sha }}"
          }
        commitChange: true
        message: "Update image to hazallul/spring-boot-app:${{ github.sha }}"

   


   
